
services:

  backend:
    build:
      context: ./ContinuixV1
    container_name: backend_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/nouvellebase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: NouveauMotDePasse123!
    ports:
      - "8080:8080"
    networks:
      - continuix_net

  frontend:
    build:
      context: ./ContinuixFront-endV1/Continuix
    container_name: frontend_service
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - continuix_net

networks:
  continuix_net:
 
